---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana

- name: List Kibana plugins
  shell: "/opt/kibana/bin/kibana plugin --list"
  register: installed_plugins
  when: kibana_plugins|length > 0
  changed_when: false

- name: Install Kibana plugins
  shell: "/opt/kibana/bin/kibana plugin --install {{ item.src }}"
  with_items: "{{ kibana_plugins }}"
  when: item.name not in installed_plugins.stdout
  notify: restart kibana
